CREATE DATABASE IF NOT EXISTS inf2;

USE inf2;

CREATE TABLE IF NOT EXISTS benutzer
(
    id INT PRIMARY KEY AUTO_INCREMENT,
    login VARCHAR(50) UNIQUE NOT NULL,
    passwort VARCHAR(120) NOT NULL
);

CREATE TABLE IF NOT EXISTS personen
(
    id INT PRIMARY KEY AUTO_INCREMENT,
    anrede VARCHAR(30) NOT NULL,
    vorname VARCHAR(30) NOT NULL,
    nachname VARCHAR(30) NOT NULL,
    ort VARCHAR(50) NOT NULL
)DEFAULT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';